from tkinter import *
a=Tk()
a.title('Menyu')
a.geometry('300x300')
a.configure(bg='red')
a.option_add('tearOFF',FALSE)
b=Menu()
c=Menu()
s=Menu()
s.add_command(label='Save')
s.add_command(label='Open')
c.add_cascade(label='Settings',menu=s)
c.add_separator()
c.add_command(label='Exit')
b.add_cascade(label='File',menu=c)
a.config(menu=b)
a.mainloop()